name: beecount
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  drift: ^2.20.2
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0
  intl: ^0.19.0
  fl_chart: ^0.68.0
  shared_preferences: ^2.3.2
  csv: ^5.0.2
  file_picker: ^8.1.2
  supabase_flutter: ^2.5.6
  crypto: ^3.0.5
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.10
  drift_dev: ^2.20.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/config.json
    - assets/logo.svg
    - assets/logo.png
    - assets/logo_cute_bee.svg
    - assets/logo_cool_bee.svg
    - assets/logo_bee_coin.svg
